mode: inference
device: cpu
pretrained: ./data/ocr_recognition/model.pth
mean: [36.8, 36.8, 36.8]
std: [77.8, 77.8, 77.8]
image_size: [140, 35]
data: {vocabulary: ./data/ocr_recognition/basic.json}
model: {backbone: SimpleNet ,sequence: BiLSTM, use_transformer: True,
        pool: {name: AvgPool, factor: 6},
        prediction: CTC, input_channel: 3, output_channel: 512,
        hidden_size: 256, num_class: 2, num_fiducial: 20}
transformer: {num_head: 2, inp_channel: 512, hidden_size: 256,
              num_layer: 2, dropout: 0.2}